export const CommonAction = {
    GET_DATA: 'GET_DATA',
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_DATA_FAIL: "GET_DATA_FAIL",
    GET_MORE_DATA_SUCCESS: "GET_MORE_DATA_SUCCESS",
    GET_MORE_DATA_FAIL: "GET_MORE_DATA_FAIL",
    TRIGGER_LOADING: 'TRIGGER_LOADING',
    TRIGGER_LOADINGMORE: 'TRIGGER_LOADINGMORE',
    UPDATE_PAGINATION_LINKS: 'UPDATE_PAGINATION_LINKS'
}

export const CommonActionId = {
    GET_POPULAR_DATA: 'GET_POPULAR_DATA',
    GET_TRENDING_DATA: 'GET_TRENDING_DATA',
}